workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      vars:
        # Add any environment variables here
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild clean build -workspace "$XCODE_WORKSPACE" \
                                 -scheme "$XCODE_SCHEME" \
                                 -configuration Release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - benjamin@citlogisticssystems.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_app_store: true
        release_type: AFTER_APPROVAL

  android-workflow:
    name: Android Workflow
    environment:
      vars:
        GRADLE_FILE: build.gradle
    scripts:
      - name: Set up Android SDK
        script: |
          yes | sdkmanager "platforms;android-30"
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
      google_play:
        credentials: $GOOGLE_PLAY_CREDENTIALS
        track: internal  # or beta, production
