name: whoosh
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0" # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1 
  get: ^4.6.5
  http: 1.3.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  google_fonts: ^6.2.1

  intl: ^0.20.2
  image_picker: ^1.1.2
  geolocator: ^13.0.3
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ # Declare the entire folder
    - assets/whoosh.png # Declare individual files