name: woosh
description: "A new Flutter project."

version: 1.0.0+7

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  get: ^4.6.5
  http: ^1.3.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  google_fonts: ^6.2.1
  permission_handler: ^11.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  geolocator: ^13.0.3
  camera: ^0.10.5+9
  path_provider: ^2.1.5
  path: ^1.9.0
  geocoding: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3
  file_picker: ^9.2.1
  dio: ^5.8.0+1
  http_parser: ^4.1.2
  flex_color_scheme: ^7.0.0  # or the latest version on pub.dev
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.jpeg
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/splash.jpeg"
  remove_alpha_ios: true 
  web:
    generate: true
    image_path: "assets/logg.png"
    background_color: "#FFFFFF"
  # Optional for Android adaptive icons:
  # adaptive_icon_background: "#FFFFFF"
  # adaptive_icon_foreground: "lib/assets/images/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/ben.png
    - assets/images/
    - assets/images/gold.png
 
