-- AlterTable
ALTER TABLE `Outlet` ADD COLUMN `balance` VARCHAR(191) NULL,
    ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `kraPin` VARCHAR(191) NULL,
    ADD COLUMN `phone` VARCHAR(191) NULL;
